name: Integração contínua

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://devpro:devpro@localhost:5432/devpro

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: devpro
          POSTGRES_USER: devpro
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11.0
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.0'
        cache: pip

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup .env
      run: cp .env.example .env

    - name: Run Tests
      run: python manage.py test
